import { IAddPODetails } from "./PostPOdetail";

export interface IAddProject {
   poguid?: number,
   projectID?:	string,
    projectName?:string,
    description?:string,
    country?:number,
    startDate?:Date,
    endDate?:Date,
    status?:number,
    isOppIDCreated?:boolean,
    isTRDReceived?:	boolean,
    trdReceivedDate?:	Date,
    isCRDSent?:	boolean,
    crdSentDate?:Date,
   //  poReceivedFromAirbus?:	boolean,
   // airbusPONumber?:	string,
   //  poReceivedFromAKKA?:	boolean,
    //ltipoNumber?:	string,
    //poReceivedDate?:Date,
    //ltipoValue?:	number,
    projectValue?:	number,
    ltiValue?:	number,
    ltiOffShoringPercentage?: number,
    ltiOffShoring?:	number,
    akkaContribution?:	number,
    akkaContractualMargin?:	number,
    akkaRevenue?:	number,
    currencyID?:number,
    invoiceNumber?:	string,
    invoiceValue?:	number,
    invoiceDate?:	Date,
    invoiceValue_VAT?:	number,
    isInvoiceSent?:	boolean,
    isPaymentDone?:	boolean,
     poDetailsList : IAddPODetails[]
}

// export class AddProject implements IAddProject{
//     constructor(
//         public projectID=	'',
//         public projectName=	'',
//         public description=	'',
//         public country=	0,
//         public startDate=new Date(),
//         public endDate=new Date(),
//         public status=	0,
//         public isOppIDCreated=false,
//         public isTRDReceived=false,
//         public trdReceivedDate=new Date(),
//         public isCRDSent=	false,
//         public crdSentDate=new Date(),
//         public poReceivedFromAirbus=	false,
//         public airbusPONumber=	'',
//         public poReceivedFromAKKA=	false,
//         public ltipoNumber=	'',
//         public poReceivedDate=new Date(),
//         public ltipoValue=	0,
//         public projectValue=	0,
//         public ltiValue=	0,
//         public ltiOffShoringPercentage= 0,
//         public ltiOffShoring=	0,
//         public akkaContribution=	0,
//         public akkaContractualMargin=0,
//         public akkaRevenue=	0,
//         public invoiceNumber=	'',
//         public invoiceValue=	0,
//         public invoiceDate=new Date(),
//         public invoiceValue_VAT=	0,
//         public isInvoiceSent=	false,
//         public isPaymentDone=	false
//     ){}
// }